name: Package and Publish
on:
  workflow_dispatch:
jobs:
  build-linux:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.13'
      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --strip --interpreter python3.13
      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: pyprc
          path: target/wheels/pyprc*.whl
        
